### ISSUE TITLE
Whether to consider implement mgo interface use the mongo-go-driver?

### ISSUE THREAD

**Issue by ansoda** [amorist/mango#11]

**Comment by amorist** [comment]
Can you provide an example?

**Comment by aegsea** [comment]
https://godoc.org/github.com/globalsign/mgo
I use a lot of mgo apis in the project, I wonder if it is possible to implement the api interface of mgo through https://godoc.org/go.mongodb.org/mongo-driver/mongo.

**Comment by amorist** [comment]
I have only implemented some common mgo apis use mongo-driver/mongo.
https://godoc.org/github.com/amorist/mango

**Comment by aegsea** [comment]
If you can  implement most of the Session, Query, Pipe, Collection, Database interface just fine.And I think the mgo interface is easier to use than the mongo-go-driver interface.

**Comment by aegsea** [comment]
Because mgo has been used in many projects, I think it is very meaningful to implement the mgo interface. There should be a lot of people who will use it.

**Comment by amorist** [comment]
Yes, I will be

**Comment by aegsea** [comment]
Ok,thanks!

**Comment by qiankunxienb** [comment]
@ansoda it seems that he didn't keep to implement the other apis. this project is unmaintained for about 17 months.

**Comment by amorist** [comment]
@ansoda https://github.com/qiniu/qmgo
